### PR TITLE
Markdown refactor for ease of access and readability

### PR DESCRIPTION
**Pull request by blake-nx**
- Created a recipes directory.
- Converted plain text files to markdown and formatted them for readability.
- Created a readme with an index file for quickly finding and accessing recipes.
2023-11-29_12h06_56

2023-11-29_12h07_03

### CODE REVIEW

**Comment by blake-nx** [comment]
@dwbapst Do you want me to close this PR?

**Comment by dwbapst** [comment]
No, don't close it. I will probably merge when I have time review these changes. At the moment though, I have a lot of grading to do...

**Comment by blake-nx** [comment]
Godspeed!

**Review by dwbapst — APPROVED** [review]
Okay, I guess its fine, but I think moving the file so it keeps the git history would have been nice rather than losing the git history. Don't worry about it now, just not sure git will be able to realize this was move-then-change-file-name.

**Comment by blake-nx** [comment]
@dwbapst Fun fact, the name _or_ the extension changing will make it look like the old one was deleted. Because as far as git knows, you deleted one file e.g. `forty-eight_hour_sourdough.txt`, and then created a new one `forty-eight_hour_sourdough.md`. Example:
image
2024-01-02_18h28_16

**Comment by blake-nx** [comment]
Closing this as it looks like it was merged some other way

**Comment by dwbapst** [comment]
Actually, that's not quite true! git can be very intelligent and usually
can detect mv transitions that otherwise appear to be add/delete in the
commit logs.

I have not merged it some other way. Yet.
-Dave

**Comment by dwbapst** [comment]
The main problem is there's some conflicts in my attempt to merge but my
fixes have actually created more branch conflicts.

**Pull request closed without merging**
